### ISSUE TITLE
Issue with chart 'charts/jupyter-r'  python imports

### ISSUE THREAD

**Issue by samuelfooks** [InseeFrLab/helm-charts-interactive-services#136]
Hello,

Starting this instance as it is with no particular configurations.  Installing python libraries works fine.  However trying to import them doesn't work

![Screenshot from 2024-04-23 12-26-50](https://github.com/InseeFrLab/helm-charts-interactive-services/assets/54527099/4c2e33bc-b2eb-4c53-a8b8-6f9a51b07394)
![Screenshot from 2024-04-23 12-26-38](https://github.com/InseeFrLab/helm-charts-interactive-services/assets/54527099/4577f1cc-8480-44ef-a0af-769dd611c2c7)

After seeing the warning, I opened a terminal in the same session and then 
nano ~/.bashrc
export PATH=$PATH:/home/onyxia/.local/bin
source ~/.bashrc.

Then installation and importing works fine

![Screenshot from 2024-04-24 08-37-09](https://github.com/InseeFrLab/helm-charts-interactive-services/assets/54527099/0f586ba5-4cbd-475b-99b8-7285b5bca52c)

I guess these instances should be created with this PATH in bashrc. Could this be adjusted? 

I received this issue from a colleague, apparently the R kernels work fine.  It was only the python kernels that had 'issues'

Thanks!

**Comment by avouacr** [comment]
Hi @samuelfooks, thank you for the feedback. It is fixed in [this commit](https://github.com/InseeFrLab/images-datascience/commit/4da00b8a1919065f8f53f6356814796a8044f253) (this concerns the datascience docker images and not the helm charts, so the relevant repository is [images-datascience](https://github.com/InseeFrLab/images-datascience). It should be fixed on Monday when our images are rebuilt.
